resources:
  cpu: 500m
  memory: 1024Mi

config:
  username: username
  password: password
  database: test

volumeset:
  capacity: 10 # initial capacity in GiB (minimum is 10)

backup:
  enabled: false
  schedule: "0 2 * * *"   # daily at 2am UTC

  resources:
    cpu: 250m
    memory: 512Mi

  aws:
    enabled: false
    s3:
      bucket: pg-backups
      region: us-east-1
      cloudAccountName: pg-backup-cloudaccount
      policyName: pg-backup-policy 
      prefix: postgres/my-cluster

  gcp:
    enabled: false
    gcs:
      bucket: pg-backups
      cloudAccountName: pg-backup-cloudaccount
      prefix: postgres/my-cluster