kind: secret
name: {{ include "postgis.secretDatabaseName" . }}
description: PostGIS database config
tags: {{- include "postgis.tags" . | nindent 4 }}
type: dictionary
data:
  username: {{ .Values.config.username }}
  password: {{ .Values.config.password }}