kind: secret
name: {{ include "maria.secretDatabaseName" . }}
description: MariaDB database configuration
tags:
  {{- include "maria.tags" . | nindent 4 }}
type: dictionary
data:
  MYSQL_DATABASE: {{ .Values.config.db }}
  MYSQL_ROOT_PASSWORD: {{ .Values.config.rootPassword }}
  MYSQL_USER: {{ .Values.config.user }}
  MYSQL_PASSWORD: {{ .Values.config.password }}