resources:
  minCpu: 200m
  maxCpu: 500m
  minMemory: 128Mi
  maxMemory: 256Mi

timeoutSeconds: 15

config:
  db: db
  rootPassword: root-pw
  user: user
  password: pw

internalAccess: # Sets the internal firewall scope - if set to none, replicas will not be able to reach each other
  type: same-gvc # options: none, same-gvc, same-org, workload-list
  workloads:  # Note: can only be used if type is same-gvc or workload-list
    #- //gvc/GVC_NAME/workload/WORKLOAD_NAME
    #- //gvc/GVC_NAME/workload/WORKLOAD_NAME

volumeset:
  capacity: 10 # initial capacity in GiB (minimum is 10)

enablePhpMyAdmin: false # set to true to enable PhpMyAdmin as an admin interface
