resources:
  minCpu: 200m
  maxCpu: 500m
  minMemory: 128Mi
  maxMemory: 256Mi

timeoutSeconds: 15

config:
  db: db
  rootPassword: root-pw
  user: user
  password: pw

volumeset:
  capacity: 10 # initial capacity in GiB (minimum is 10)

enablePhpMyAdmin: false # set to true to enable PhpMyAdmin as an admin interface
