# {{- if .Values.locations }}
# {{- else }}
# kind: secret
# name: {{ include "redis.secretConfigName" . }}
# type: opaque
# data:
#   encoding: plain
#   payload: |-
#     bind 0.0.0.0
#     protected-mode no
#     port 6379
#     save 900 1
#     save 300 10
#     save 60 10000
#     appendonly yes
# {{- end }}