kind: secret
name: {{ include "rabbitmq.secretName" . }}
type: opaque
data:
  encoding: plain
  payload: |-
    listeners.tcp.default = {{ .Values.rabbitmq_conf.listeners_tcp_default }}
    default_user = {{ .Values.rabbitmq_conf.default_user }}
    default_pass = {{ .Values.rabbitmq_conf.default_pass }}
