gvc:
  name: clickhouse-gvc
  # Replica count will only affect the server workload
  # Keeper will always have 3 total replicas (1 per location)
  locations: # Minimum of 3 locations are required
    - name: aws-us-west-2
      replicas: 1
    - name: aws-us-east-2
      replicas: 1
    - name: aws-us-east-1
      replicas: 1

aws:
  enabled: false # Enable to use S3 for storage
  s3: # If enabled, all fields below are required - See README for guidance
    bucket: clickhouse-s3-bucket # Name of your S3 bucket
    region: us-east-1 # Region of your S3 bucket
    cloudAccountName: clickhouse-s3-cloudaccount # Name of your Cloud Account
    policyName: clickhouse-s3-policy # Name of your pre-created policy to allow access to the S3 bucket

gcp:
  enabled: false # Enable to use GCS for storage
  gcs: # If enabled, all fields below are required - See README for guidance
    bucket: clickhouse-gcs-bucket # Name of your GCS bucket
    accessKeyId: gcs-access-key-id # Access key ID for your GCS service account
    secretAccessKey: gcs-secret-access-key # Secret access key for your GCS service account

clusterName: my_cluster # Name of ClickHouse cluster

database: # Automatically create a database on initialization using the default user
  name: mydatabase
  password: mypassword

volumeset:
  server:
    capacity: 10 # initial capacity in GiB (minimum is 10)
  keeper:
    capacity: 10 # initial capacity in GiB (minimum is 10)

server:
  resources:
    cpu: 2
    memory: 2Gi
  internal_access:
    type: same-gvc # options: same-gvc, same-org, workload-list
    workloads:  # Note: can only be used if type is same-gvc or workload-list
      #- //gvc/GVC_NAME/workload/WORKLOAD_NAME
      #- //gvc/GVC_NAME/workload/WORKLOAD_NAME

keeper:
  resources:
    cpu: 2
    memory: 2Gi
  internal_access:
    type: same-gvc # options: same-gvc, same-org, workload-list
    workloads:  # Note: can only be used if type is same-gvc or workload-list
      #- //gvc/GVC_NAME/workload/WORKLOAD_NAME
      #- //gvc/GVC_NAME/workload/WORKLOAD_NAME