{{- if .Values.locations }}
{{- else }}
kind: secret
name: {{ include "redis.sentinelSecretConfigName" . }}
description: Sentinel Secret Config
tags: {{- include "redis.tags" . | nindent 4 }}
type: opaque
data:
  encoding: plain
  payload: |-
    port 26379
    dir /tmp
    sentinel announce-hostnames yes
    sentinel resolve-hostnames yes
    sentinel down-after-milliseconds mymaster 5000
    sentinel failover-timeout mymaster 10000
    sentinel parallel-syncs mymaster 1
    {{- if .Values.redis.password }}
    sentinel auth-pass mymaster {{ .Values.redis.password }}
    {{- end }}
    {{- if .Values.sentinel.password }}
    requirepass {{ .Values.sentinel.password }}
    {{- end }}
{{- end }}