image: mongo:6.0

resources:
  cpu: 500m
  memory: 1024Mi

config:
  username: username
  password: password

volumeset:
  capacity: 10 # initial capacity in GiB (minimum is 10)

directLoadBalancer:
  enabled: false