kind: secret
name: {{ include "mongo.secretDatabaseName" . }}
description: MongoDB database configuration
tags:
  {{- include "mongo.tags" . | nindent 4 }}
type: dictionary
data:
  username: {{ .Values.config.username }}
  password: {{ .Values.config.password }}
