---
kind: secret
name: {{ include "clickhouse.secretDatabaseName" . }}
description: Clickhouse database config
tags: {{- include "clickhouse.tags" . | nindent 4 }}
type: dictionary
data:
  password: {{ .Values.database.password }}
  db: {{ .Values.database.name }}
  cluster_name: {{ .Values.clusterName }}