{{- if .Values.aiConfigurator.enabled }}
---
kind: workload
name: {{ .Release.Name }}-ai-tyk-configurator
description: AI Tyk Configurator
tags: {{- include "tyk.tags" . | nindent 4 }}
spec:
  type: standard
  containers:
    - name: ai-tyk-configurator
      cpu: 500m
      env:
        - name: APIS_PATH
          value: /opt/tyk-gateway/apps
        - name: POLICIES_PATH
          value: /opt/tyk-gateway/policies
        - name: PORT
          value: '3000'
        - name: TYK_GATEWAY_WORKLOAD
          value: {{ .Release.Name }}-tyk-api-gateway.{{ .Values.global.cpln.gvc }}.cpln.local
        - name: TYK_RELOAD_SECRET
          value: cpln://secret/{{ .Release.Name }}-tyk-gateway-secret.admin-secret
        - name: ANTHROPIC_API_KEY
          value: cpln://secret/{{ .Release.Name }}-tyk-gateway-secret.anthropic-api-key
      image: jacobcox/tyk-configurator:1.2
      inheritEnv: false
      memory: 512Mi
      ports:
        - number: 3000
          protocol: http
      volumes:
        - path: /opt/tyk-gateway/apps
          recoveryPolicy: retain
          uri: cpln://volumeset/{{ .Release.Name }}-tyk-apis-vs
        - path: /opt/tyk-gateway/policies
          recoveryPolicy: retain
          uri: cpln://volumeset/{{ .Release.Name }}-tyk-policies-vs
  defaultOptions:
    autoscaling:
      keda:
        cooldownPeriod: 1
        initialCooldownPeriod: 1
        pollingInterval: 1
        triggers: []
      maxConcurrency: 0
      maxScale: 3
      metric: cpu
      minScale: 1
      scaleToZeroDelay: 300
      target: 100
    capacityAI: false
    debug: false
    suspend: false
    timeoutSeconds: 5
  firewallConfig:
    external:
      inboundAllowCIDR:
        - 0.0.0.0/0
      inboundBlockedCIDR: []
      outboundAllowCIDR: []
      outboundAllowHostname: []
      outboundAllowPort: []
      outboundBlockedCIDR: []
    internal:
      inboundAllowType: {{ .Values.internal_access.type }}
      {{- if .Values.internal_access.workloads }}
      inboundAllowWorkload: {{ .Values.internal_access.workloads | toYaml | nindent 8 }}
      {{- end }}
  identityLink: //gvc/{{ .Values.global.cpln.gvc }}/identity/{{ .Release.Name }}-tyk-identity
  loadBalancer:
    direct:
      enabled: false
      ports: []
    replicaDirect: false
  supportDynamicTags: false
{{- end }}